### ISSUE TITLE
routing does not initialize properly 

### ISSUE THREAD

**Issue by hew** [hew/reasonable-website#1]
If you are on, say, `/repos` and you load the app for the first time, no beuno — you will see the `home` route, not the `repos` one.

**Comment by thangngoc89** [comment]
Solution:

`initialState: () => { route: ReasonReact.Router.dangerouslyGetInitialUrl() |> mapUrlToRoute }`

And this requires reason-react>0.3.2

**Comment by hew** [comment]
Nice idea 😎. Thanks @thangngoc89!
